// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.1
//   protoc               v3.20.3
// source: apps/wrapper-controller/src/v1/grpc/protos/user.proto

/* eslint-disable */
import { Metadata } from '@grpc/grpc-js';
import { GrpcMethod, GrpcStreamMethod } from '@nestjs/microservices';
import { Observable } from 'rxjs';

export const protobufPackage = 'vn.grpc.nodejs.user.service';

export interface SignUpDTO {
  email: string;
  password: string;
}

export interface BaseResponse {
  status: number;
  message: string;
  data: BasicToken | undefined;
}

export interface BasicToken {
  basicToken: string;
}

export const VN_GRPC_NODEJS_USER_SERVICE_PACKAGE_NAME = 'vn.grpc.nodejs.user.service';

export interface UserServiceClient {
  signUp(request: SignUpDTO, metadata?: Metadata): Observable<BaseResponse>;
}

export interface UserServiceController {
  signUp(request: SignUpDTO, metadata?: Metadata): Promise<BaseResponse> | Observable<BaseResponse> | BaseResponse;
}

export function UserServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ['signUp'];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod('UserService', method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod('UserService', method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const USER_SERVICE_NAME = 'UserService';
